# Generated by Django 4.2.7 on 2023-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date_posted", models.DateField()),
                ("date_applied", models.DateField()),
                ("job_url", models.CharField(max_length=100)),
                ("job_description", models.CharField(max_length=1000)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("interview", "Interview Scheduled"),
                            ("offer", "Job Offered"),
                            ("rejected", "Application Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
