# Generated by Django 4.2.7 on 2023-11-12 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0006_jobapplication_date_added_to_database"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="date_added_to_database",
            new_name="date_added_to_db",
        ),
    ]
