# Generated by Django 4.2.7 on 2023-11-12 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0008_remove_jobapplication_date_added_to_db"),
    ]

    operations = [
        migrations.AddField(
        model_name='jobapplication',
        name='date_added_to_db',
        field=models.DateField(default=django.utils.timezone.now),
        preserve_default=True,
        ),
    ]
