# Generated by Django 4.2.7 on 2023-11-12 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("job_applications", "0009_jobapplication_date_added_to_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="date_added_to_db",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
