proxies: {}

headers: {}

OpenAI_API_KEY: ""

OpenAI_Model: ""

resume_path: "full local path to your resume in PDF format"

search_queries:
  - keywords: "Software Developer"
    location: "Canada"
    f_WT: ""
  - keywords: "Software Engineer"
    location: "USA"
    f_WT: "2"

desc_words:
  - agriculture
  - farm
  - food safety
  - manufacture
  - manufacturing
  - Bilingual
  - chemistry
  - FDA
  - ICH Guideline
  - 21 CFR 210
  - biological sciences
  - clinical research
  - clinical trials
  - drug safety
  - ISO 9001
  - ISO9001
  - Life Sciences
  - Biotech
  - safety standards
  - gt.school
  - degree in accounting
  - degree in Finance
  - ISQM
  - ISQM1
  - QA/QC
  - Electrical Engineering
  - IS09001

title_exclude:
  - frontend
  - fron end
  - game

title_include:
  - python
  - developer
  - backend
  - BE
  - engineer

company_exclude:
  - ClickJobs.io

languages:
  - en

timespan: "r84600"

jobs_tablename: "jobs"

filtered_jobs_tablename: "filtered_jobs"

db_path: "./data/my_database.db"

pages_to_scrape: 10

rounds: 1

days_to scrape: 10

app_table: "jobs"


# work_preference:
#     REMOTE: true
#     ON_SITE: true
#     HYBRID: false
#   JOB_TITLE: "(javascript|frontend|front-end|fullstack|full-stack|nodejs|node|js).*(developer|engineer)"
#   JOB_TITLE_EXCLUDE: "(clinic|healthcare)"
#   JOB_DESCRIPTION: "^((?!(primeit))(.|[\n\r]))*$"
#   JOB_DESCRIPTION_LANGUAGES:
#     - "english" 
#   COMPANY_EXCLUDE: 
#     - "Clickjobs.IO"

# formData:
#   PHONE: "912345678"
#   CV_PATH: ""
#   COVER_LETTER_PATH: ""
#   HOME_CITY: "Lisbon, Portugal"
#   YEARS_OF_EXPERIENCE:
#     angular: 5
#     react: 6
#     dotnet: 3
#     php: 4
#     spring: 4
#     java: 4
#     magento: 5
#     node: 5
#     javascript: 5
#     mongodb: 5
#     kubernetes: 5
#     CICD: 5
#     python: 5
#     drupal: 5
#     sass: 5
#     html: 5
#     googlecloud: 5
#     docker: 5
#     terraform: 5
#     css: 4
#     typescript: 6
#     webmethods: 5

#   LANGUAGE_PROFICIENCY:
#     english: "professional"
#     spanish: "native"
#     french: "native"
#   REQUIRES_VISA_SPONSORSHIP: false
#   TEXT_FIELDS:
#     salary: "60k"
#   BOOLEANS:
#     bachelhor|bacharelado: true
#     authorized: true
#   MULTIPLE_CHOICE_FIELDS:
#     pronouns: "They/them"

#   # OTHER SETTINGS
#   SINGLE_PAGE: false